/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab9p2;

import java.awt.event.ActionEvent;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author adony
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        hilofechahora hilohorafecha = new hilofechahora(hora, fecha);
        hilohorafecha.start();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelrojo = new javax.swing.JPanel();
        paneblanco = new javax.swing.JPanel();
        bienvenido = new javax.swing.JLabel();
        labelfechahoy = new javax.swing.JLabel();
        fecha = new javax.swing.JLabel();
        labelfechaactual = new javax.swing.JLabel();
        hora = new javax.swing.JLabel();
        subirarchivo = new javax.swing.JButton();
        barra_Progreso = new javax.swing.JProgressBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        area_texto = new javax.swing.JTextArea();
        guardar = new javax.swing.JButton();
        labelnombredunai = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelrojo.setBackground(new java.awt.Color(255, 0, 0));

        paneblanco.setBackground(new java.awt.Color(255, 255, 255));
        paneblanco.setForeground(new java.awt.Color(255, 255, 255));

        bienvenido.setForeground(new java.awt.Color(0, 0, 0));
        bienvenido.setText("Bienvenido");

        labelfechahoy.setForeground(new java.awt.Color(0, 0, 0));
        labelfechahoy.setText("Fecha de Hoy:");

        fecha.setForeground(new java.awt.Color(0, 0, 0));
        fecha.setText("-----------");

        labelfechaactual.setForeground(new java.awt.Color(0, 0, 0));
        labelfechaactual.setText("Hora actual:");

        hora.setForeground(new java.awt.Color(0, 0, 0));
        hora.setText("-----------");

        javax.swing.GroupLayout paneblancoLayout = new javax.swing.GroupLayout(paneblanco);
        paneblanco.setLayout(paneblancoLayout);
        paneblancoLayout.setHorizontalGroup(
            paneblancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneblancoLayout.createSequentialGroup()
                .addGroup(paneblancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneblancoLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(bienvenido, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneblancoLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneblancoLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(paneblancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(paneblancoLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(hora, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(paneblancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(labelfechahoy, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneblancoLayout.createSequentialGroup()
                                    .addComponent(labelfechaactual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(29, 29, 29))))))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        paneblancoLayout.setVerticalGroup(
            paneblancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneblancoLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(bienvenido)
                .addGap(18, 18, 18)
                .addComponent(labelfechahoy)
                .addGap(18, 18, 18)
                .addComponent(fecha)
                .addGap(18, 18, 18)
                .addComponent(labelfechaactual)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hora)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        subirarchivo.setBackground(new java.awt.Color(255, 255, 255));
        subirarchivo.setForeground(new java.awt.Color(0, 0, 0));
        subirarchivo.setText("Subir Archivos");
        subirarchivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                subirarchivoMouseClicked(evt);
            }
        });

        barra_Progreso.setBackground(new java.awt.Color(255, 102, 51));

        area_texto.setBackground(new java.awt.Color(255, 255, 255));
        area_texto.setColumns(20);
        area_texto.setForeground(new java.awt.Color(0, 0, 0));
        area_texto.setRows(5);
        jScrollPane1.setViewportView(area_texto);

        guardar.setBackground(new java.awt.Color(255, 255, 255));
        guardar.setForeground(new java.awt.Color(0, 0, 0));
        guardar.setText("Guardar");
        guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guardarMouseClicked(evt);
            }
        });

        labelnombredunai.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelnombredunai.setForeground(new java.awt.Color(255, 255, 255));
        labelnombredunai.setText("Dunai Cloud DBD");

        javax.swing.GroupLayout panelrojoLayout = new javax.swing.GroupLayout(panelrojo);
        panelrojo.setLayout(panelrojoLayout);
        panelrojoLayout.setHorizontalGroup(
            panelrojoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelrojoLayout.createSequentialGroup()
                .addComponent(paneblanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelrojoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelrojoLayout.createSequentialGroup()
                        .addGroup(panelrojoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelrojoLayout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addGroup(panelrojoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(subirarchivo)
                                    .addComponent(barra_Progreso, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelrojoLayout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 105, Short.MAX_VALUE))
                    .addGroup(panelrojoLayout.createSequentialGroup()
                        .addGroup(panelrojoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelrojoLayout.createSequentialGroup()
                                .addGap(309, 309, 309)
                                .addComponent(guardar))
                            .addGroup(panelrojoLayout.createSequentialGroup()
                                .addGap(271, 271, 271)
                                .addComponent(labelnombredunai, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panelrojoLayout.setVerticalGroup(
            panelrojoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneblanco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelrojoLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(labelnombredunai, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(subirarchivo)
                .addGap(18, 18, 18)
                .addComponent(barra_Progreso, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(guardar)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelrojo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelrojo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void subirarchivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subirarchivoMouseClicked

        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Hola juan selecciona un txt", "txt"));
        int seleccion = fileChooser.showOpenDialog(null);
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            archivoSeleccionado = fileChooser.getSelectedFile();
            Progreso actualizador = new Progreso(barra_Progreso, archivoSeleccionado, area_texto);
            actualizador.start();
        }
    }//GEN-LAST:event_subirarchivoMouseClicked
    private File archivoSeleccionado;
    private void guardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardarMouseClicked
         if (archivoSeleccionado != null) {
            try {
                BufferedWriter bw = new BufferedWriter(new FileWriter(archivoSeleccionado));
                bw.write(area_texto.getText());
                bw.close();
                JOptionPane.showMessageDialog(rootPane, "Guardado con exito");
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        } else {
             JOptionPane.showMessageDialog(rootPane, "No hay ningun archivo seleccionado");
        }
    }//GEN-LAST:event_guardarMouseClicked

/**
 * @param args the command line arguments
 */
public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

}
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea area_texto;
    private javax.swing.JProgressBar barra_Progreso;
    private javax.swing.JLabel bienvenido;
    private javax.swing.JLabel fecha;
    private javax.swing.JButton guardar;
    private javax.swing.JLabel hora;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelfechaactual;
    private javax.swing.JLabel labelfechahoy;
    private javax.swing.JLabel labelnombredunai;
    private javax.swing.JPanel paneblanco;
    private javax.swing.JPanel panelrojo;
    private javax.swing.JButton subirarchivo;
    // End of variables declaration//GEN-END:variables
}
